# Server Configuration
server.port=9000

# Application Configuration
app.reports.directory=/home/timothy/reports
app.reports.scan-interval=2000

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Logging
logging.level.uk.creswick.luumo.pireporting=DEBUG
logging.level.org.springframework.web=INFO
